Schibsted.TechnicalTest.WebSite/Models/ErrorViewModel.cs
namespace Schibsted.TechnicalTest.WebSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Schibsted.TechnicalTest.WebSite/Models/LoginViewModel.cs
namespace Schibsted.TechnicalTest.WebSite.Models
{
    using System.ComponentModel.DataAnnotations;

    public class LoginViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

Schibsted.TechnicalTest.WebSite/Controllers/AccountController.cs
namespace Schibsted.TechnicalTest.WebSite.Controllers
{
    using System.Text.Encodings.Web;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Schibsted.TechnicalTest.Core.Abstractions;
    using Schibsted.TechnicalTest.Infrastructure.Extensions;
    using Schibsted.TechnicalTest.WebSite.Models;

    [Route("[controller]/[action]")]
    public class AccountController : Controller
    {
        private readonly HtmlEncoder _encoder;
        private readonly ILogger<AccountController> _logger;
        private readonly IAuthenticationService _authenticationService;

        public AccountController(
            HtmlEncoder htmlEncoder,
            ILogger<AccountController> logger,
            IAuthenticationService authenticationService)
        {
            _logger = logger;
            _encoder = htmlEncoder;
            _authenticationService = authenticationService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> Login(string returnUrl = null)
        {
            await SignInExtensions.SignOutAsync(HttpContext);

            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (await _authenticationService.LoginUserAsync(model.Username, model.Password, HttpContext))
            {
                return RedirectToLocal(returnUrl);
            }

            ModelState.AddModelError(string.Empty, "Please, review user and password combination");
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Logout()
        {
            await SignInExtensions.SignOutAsync(HttpContext);

            _logger.LogInformation("User logged out.");
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        [HttpGet]
        public ActionResult AccessDenied()
        {
            return View();
        }

        protected ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController));
        }
    }
}

Schibsted.TechnicalTest.WebSite/Controllers/HomeController.cs
namespace Schibsted.TechnicalTest.WebSite.Controllers
{
    using System.Diagnostics;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Schibsted.TechnicalTest.Common.Model;
    using Schibsted.TechnicalTest.WebSite.Models;

    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Schibsted.TechnicalTest.WebSite/Controllers/Page1Controller.cs
namespace Schibsted.TechnicalTest.WebSite.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Schibsted.TechnicalTest.Common.Model;

    [Authorize(Policy = nameof(RoleType.Page1))]
    public class Page1Controller : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Schibsted.TechnicalTest.WebSite/Controllers/Page2Controller.cs
namespace Schibsted.TechnicalTest.WebSite.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Schibsted.TechnicalTest.Common.Model;

    [Authorize(Policy = nameof(RoleType.Page2))]
    public class Page2Controller : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Schibsted.TechnicalTest.WebSite/Controllers/Page3Controller.cs
namespace Schibsted.TechnicalTest.WebSite.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Schibsted.TechnicalTest.Common.Model;

    [Authorize(Policy = nameof(RoleType.Page3))]
    public class Page3Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Schibsted.TechnicalTest.WebSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<partial name="_PagePartial" />

<div style="margin-top: 10px">
    @{
        if (User.IsInRole(nameof(RoleType.Page1)))
        {
            <a class="btn btn-primary" asp-controller="Page1">Go to Page1</a>
        }

        if (User.IsInRole(nameof(RoleType.Page2)))
        {
            <a class="btn btn-primary" asp-controller="Page2">Go to Page2</a>
        }

        if (User.IsInRole(nameof(RoleType.Page3)))
        {
            <a class="btn btn-primary" asp-controller="Page3">Go to Page3</a>
        }
    }
</div>

Schibsted.TechnicalTest.WebSite/Views/Page1/Index.cshtml
@{
    ViewData["Title"] = "Page 1";
}

<h1>Page 1</h1>

<partial name="_PagePartial"/>

Schibsted.TechnicalTest.WebSite/Views/Page2/Index.cshtml
@{
    ViewData["Title"] = "Page 2";
}

<h1>Page 2</h1>

<partial name="_PagePartial" />

Schibsted.TechnicalTest.WebSite/Views/Page3/Index.cshtml
@{
    ViewData["Title"] = "Page 3";
}

<h1>Page 3</h1>

<partial name="_PagePartial" />

Schibsted.TechnicalTest.WebSite/Views/Shared/AccessDenied.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AccessDenied</title>
</head>
<body>
    <h1>You do not have enough privileges to see this page</h1>
</body>
</html>

Schibsted.TechnicalTest.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Schibsted TechincalTest</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Schibsted TechincalTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Schibsted TechincalTest (Victor Martin)
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Schibsted.TechnicalTest.WebSite/Views/Shared/_PagePartial.cshtml
<h4>Hello @User.Identity.Name</h4>

<div style="margin-top: 10px">
    <form asp-controller="Account" asp-action="Logout" method="post">
        <button class="btn btn-info" type="submit">Logout</button>
    </form>
</div>